/**
 * The guard on the published page's link preview.
 *
 * The demo is where every link in the README, the package metadata and the
 * repository description points, so it is the one page whose preview is a
 * marketing asset rather than a nicety. The failure it exists to catch is not a
 * crash: `frames` exits 0 having written a page whose card tags are empty, the
 * site deploys, and the only symptom is that every share of it for the next
 * month is a bare url. Nobody notices from inside the page.
 *
 * Pure, so it tests without building a site. The runner does the reading.
 */

import assert from "node:assert/strict";
import { describe, it } from "node:test";

import { cardBytesOf, cardProblems } from "../tools/demo-card.mjs";

const SITE = "https://danhnm1203.github.io/scrollytelling/";

/** A head with every tag filled the way a good build leaves it. */
function page(overrides = {}) {
  const tags = {
    "og:title": "scrollytelling — a video, scrubbed by scroll",
    "og:description": "Generated by one command from a clip.",
    "og:url": SITE,
    "og:image": `${SITE}og.jpg`,
    "twitter:card": "summary_large_image",
    "twitter:image": `${SITE}og.jpg`,
    ...overrides,
  };
  const meta = Object.entries(tags)
    .filter(([, value]) => value !== null)
    .map(([key, value]) => `<meta property="${key}" content="${value}" />`)
    .join("\n    ");
  return `<html><head>\n    ${meta}\n  </head><body></body></html>`;
}

describe("the published page's card", () => {
  it("passes a page that carries a complete card", () => {
    assert.deepEqual(cardProblems(page(), { siteUrl: SITE, cardBytes: 52_000 }), []);
  });

  it("catches the empty tags a successful build can still leave", () => {
    // The exact shape of the failure: exit 0, a page that renders, and a
    // preview that says nothing.
    const problems = cardProblems(page({ "og:image": "", "og:url": "" }), {
      siteUrl: SITE,
      cardBytes: 52_000,
    });
    assert.equal(problems.length, 2);
    assert.ok(problems.some((p) => p.includes("og:image")));
    assert.ok(problems.some((p) => p.includes("og:url")));
  });

  it("catches a relative image, which looks right and resolves to nothing", () => {
    const problems = cardProblems(page({ "og:image": "og.jpg" }), {
      siteUrl: SITE,
      cardBytes: 52_000,
    });
    assert.ok(problems.some((p) => /og:image/.test(p) && /absolute/.test(p)));
  });

  it("catches an image pointing somewhere other than this site", () => {
    // A stale origin from a previous deploy target is live markup pointing at
    // somebody else's server, which is worse than empty.
    const problems = cardProblems(page({ "og:image": "https://elsewhere.test/og.jpg" }), {
      siteUrl: SITE,
      cardBytes: 52_000,
    });
    assert.ok(problems.some((p) => p.includes("elsewhere.test")));
  });

  it("catches a tag the page lost altogether", () => {
    const problems = cardProblems(page({ "og:image": null }), {
      siteUrl: SITE,
      cardBytes: 52_000,
    });
    assert.ok(problems.some((p) => /og:image/.test(p) && /missing/.test(p)));
  });

  it("catches a card file that was never written", () => {
    const problems = cardProblems(page(), { siteUrl: SITE, cardBytes: null });
    assert.ok(problems.some((p) => /card/.test(p) && /not/.test(p)));
  });

  it("catches a card file that is there but empty", () => {
    // A zero-byte jpeg satisfies "the file exists" and unfurls as nothing.
    const problems = cardProblems(page(), { siteUrl: SITE, cardBytes: 0 });
    assert.ok(problems.some((p) => /card/.test(p)));
  });

  it("accepts a url the CLI normalised out from under it", () => {
    // `frames` runs the value through new URL(): the scheme and host come back
    // lowercased and a trailing slash is added. Comparing the page against the
    // RAW argument therefore fails a page that is perfectly correct, and the
    // build stops on a good deploy. Found in review, not by a test — this is
    // the test.
    const problems = cardProblems(page(), { siteUrl: "HTTPS://DanhNM1203.github.io/scrollytelling", cardBytes: 52_000 });
    assert.deepEqual(problems, []);
  });

  it("does not mistake a sibling path for being under the site", () => {
    // A prefix test says https://host/scrollytelling-other/og.jpg is under
    // https://host/scrollytelling/. It is a different site.
    const problems = cardProblems(
      page({ "og:image": "https://danhnm1203.github.io/scrollytelling-other/og.jpg" }),
      { siteUrl: SITE, cardBytes: 52_000 },
    );
    assert.ok(problems.some((p) => p.includes("scrollytelling-other")));
  });

  it("holds twitter:image to the same bar as og:image", () => {
    // outline.mjs writes it, so a build can get it wrong, so the guard has to
    // check it. It was missed on the first pass.
    const empty = cardProblems(page({ "twitter:image": "" }), { siteUrl: SITE, cardBytes: 52_000 });
    assert.ok(empty.some((p) => p.includes("twitter:image")));

    const foreign = cardProblems(page({ "twitter:image": "https://elsewhere.test/og.jpg" }), {
      siteUrl: SITE,
      cardBytes: 52_000,
    });
    assert.ok(foreign.some((p) => p.includes("twitter:image")));
  });

  it("says nothing when no site url was claimed", () => {
    // A local build without --site-url is not promising a card, so there is
    // nothing to hold it to. Guarding it anyway would make `npm run sample`
    // fail for everyone who just wants to look at the page.
    assert.deepEqual(cardProblems(page({ "og:image": "", "og:url": "" }), { siteUrl: null }), []);
  });

  it("reports every problem at once, not the first", () => {
    // A build that has to be re-run to find the next fault wastes an encode
    // each time, and the encode is the slow part.
    const problems = cardProblems(page({ "og:image": "", "og:title": "", "og:url": "" }), {
      siteUrl: SITE,
      cardBytes: null,
    });
    assert.ok(problems.length >= 4, `expected several, got ${problems.length}`);
  });
});

describe("what counts as a card file", () => {
  // The decision that let the real bug through. `frames` treats a card it
  // could not write as a warning rather than a failure, so the guard is the
  // only thing standing between a directory named og.jpg and a deploy. It is
  // in here, pure, rather than inline in the runner, because that is the part
  // that was wrong and untested.

  it("takes the size of a regular file", () => {
    assert.equal(cardBytesOf({ isFile: () => true, size: 52_000 }), 52_000);
  });

  it("treats a directory as no card at all", () => {
    assert.equal(cardBytesOf({ isFile: () => false, size: 64 }), null);
  });

  it("treats a missing file as no card at all", () => {
    assert.equal(cardBytesOf(undefined), null);
    assert.equal(cardBytesOf(null), null);
  });
});
