// GENERATED by `scrollytelling frames` — do not edit.
//
// This is the placeholder a fresh scaffold ships with, so the project builds
// before any footage has been processed. Running `scrollytelling frames`
// replaces it with the real sequence.
//
// Plain JavaScript, with its types in frames.d.ts. That is what lets a template
// with no build step import this directly, and it costs the TypeScript
// templates nothing.

export const LUMA_COLS = 6;
export const LUMA_ROWS = 4;

/**
 * Ordered by preference. The page picks whichever sequence best matches the
 * viewport; empty means no footage has been processed yet.
 *
 * @type {readonly import("./frames").Sequence[]}
 */
export const SEQUENCES = [];

/**
 * Where a given frame is served from.
 *
 * The frames sit beside this page, so the path is resolved against the page
 * itself: drop the directory anywhere — a GitHub Pages project site, a
 * subfolder on a static host — and it keeps working with nothing to configure.
 *
 * It resolves to an absolute url on purpose. The engine hands these strings to
 * a worker, and a worker resolves a relative url against its own script in
 * `lib/` rather than against this page, so a relative path would 404 there
 * while working fine for the poster image.
 *
 * It is still the only place the runtime learns where the frames are, so edit
 * it if you move them.
 *
 * @param {string} sequenceId
 * @param {number} index
 * @returns {string}
 */
export function framePath(sequenceId, index) {
  return new URL(`frames/${sequenceId}_${index}.webp`, document.baseURI).href;
}
