// GENERATED by `scrollytelling frames` — do not edit.
//
// This is the placeholder a fresh scaffold ships with, so the project builds
// before any footage has been processed. Running `scrollytelling frames`
// replaces it with the real sequence.

export type Sequence = {
  id: string;
  width: number;
  height: number;
  totalFrames: number;
  /** That frame's own border color. The page paints it behind the canvas. */
  edgeColors: readonly (readonly [number, number, number])[];
  /** 6 columns x 4 rows, row-major, 0..1. */
  lumaGrid: readonly (readonly number[])[];
};

export const LUMA_COLS = 6;
export const LUMA_ROWS = 4;

/**
 * Ordered by preference. The page picks whichever sequence best matches the
 * viewport; empty means no footage has been processed yet.
 */
export const SEQUENCES = [] as const satisfies readonly Sequence[];

export function framePath(sequenceId: string, index: number): string {
  return `/frames/${sequenceId}_${index}.webp`;
}
