/**
 * What the published demo page says.
 *
 * The page at the project's own url is the first thing a stranger scrolls, so
 * it should be about this tool rather than about the template's imaginary
 * product. Everything else about it is ordinary output: the same engine, the
 * same generated contract, the same four beats a scaffolded project ships with.
 *
 * The beat positions are not round numbers, and are not guesses. They came from
 * `scrollytelling frames --check`, run against the footage actually behind them:
 * it named two beats that would fight a bright portrait crop and said where the
 * frames were calmer. Those are the numbers below.
 *
 * Which means if you change the footage, re-run the check. The copy is written
 * for this page; the positions are written for tools/demo-clip.mp4:
 *
 *   node tools/sample-site.mjs --template html --frames 50 \
 *     --clip tools/demo-clip.mp4 --story tools/demo-story.js
 *   node bin/cli.mjs frames --check .sample-html
 *
 * It should say "every beat sits on footage the scrim can handle".
 */

/** @type {import("../templates/html/components/story").Story} */
export const story = {
  brand: "SCROLLYTELLING",
  title: "scrollytelling — a video, scrubbed by scroll",
  description:
    "This page was generated by one command from a clip. The frames advance as you scroll, " +
    "and every one of them was measured while it was encoded.",
  sections: [
    {
      at: 0.0,
      align: "center",
      heading: "One command",
      body: "This page was built from a video by a CLI. Keep scrolling — the clip is the page.",
    },
    {
      at: 0.32,
      align: "right",
      heading: "Every frame measured",
      body: "The background is each frame's own edge colour, so the canvas has no visible edge against the page.",
    },
    {
      at: 0.72,
      align: "left",
      anchor: "bottom",
      heading: "Copy that stays readable",
      body: "The brightness behind each block of text is measured at encode time, and the backdrop is sized to it.",
    },
    {
      at: 0.93,
      align: "center",
      anchor: "bottom",
      heading: "Next, Nuxt, Astro or plain HTML",
      body: "This one is the plain HTML template: no build step, no dependencies, no framework.",
    },
  ],
};
