// GENERATED by `scrollytelling frames` — do not edit.
//
// This is the placeholder a fresh scaffold ships with, so the project builds
// before any footage has been processed. Running `scrollytelling frames`
// replaces it with the real sequence.

export type Sequence = {
  id: string;
  width: number;
  height: number;
  totalFrames: number;
  /** That frame's own border color. The page paints it behind the canvas. */
  edgeColors: readonly (readonly [number, number, number])[];
  /** 6 columns x 4 rows, row-major, 0..1. */
  lumaGrid: readonly (readonly number[])[];
};

export const LUMA_COLS = 6;
export const LUMA_ROWS = 4;

/**
 * Ordered by preference. The page picks whichever sequence best matches the
 * viewport; empty means no footage has been processed yet.
 *
 * Annotated rather than `as const satisfies`, which is what the generated file
 * uses. An empty `as const` array is the tuple type `readonly []`, and indexing
 * a zero-length tuple is a type error — so `SEQUENCES[0]`, which every consumer
 * does, would not compile until the first sequence existed. That is precisely
 * the window a freshly scaffolded project sits in.
 *
 * The generated file keeps `as const satisfies` because by then the array has
 * entries and the extra precision is free.
 */
export const SEQUENCES: readonly Sequence[] = [];

export function framePath(sequenceId: string, index: number): string {
  return `/frames/${sequenceId}_${index}.webp`;
}
