// GENERATED by `scrollytelling frames` — do not edit.
//
// This is the placeholder a fresh scaffold ships with, so the project builds
// before any footage has been processed. Running `scrollytelling frames`
// replaces it with the real sequence.
//
// Plain JavaScript, with its types in frames.d.ts. That is what lets a template
// with no build step import this directly, and it costs the TypeScript
// templates nothing.

export const LUMA_COLS = 6;
export const LUMA_ROWS = 4;

/**
 * Ordered by preference. The page picks whichever sequence best matches the
 * viewport; empty means no footage has been processed yet.
 *
 * @type {readonly import("./frames").Sequence[]}
 */
export const SEQUENCES = [];

/**
 * Where a given frame is served from.
 *
 * Edit this if the site is deployed under a subdirectory — a GitHub Pages
 * project site, or anything with a base path. It is the only place the runtime
 * learns where the frames are, which is why it is a function you can change
 * rather than a convention baked into the engine.
 *
 * @param {string} sequenceId
 * @param {number} index
 * @returns {string}
 */
export function framePath(sequenceId, index) {
  return `/frames/${sequenceId}_${index}.webp`;
}
